#!/usr/bin/perl
# ---   *   ---   *   ---
# THRONE
# Small RTS
#
# LIBRE SOFTWARE
# Licensed under GNU GPL3
# be a bro and inherit
#
# CONTRIBUTORS
# lyeb,
# ---   *   ---   *   ---

# deps
package main;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/lib/';

  use avt;
  use lycon;
  use cash;

  # for test
  use lib $ENV{'ARPATH'}.'/THRONE/';
  use cell;
  use scene;
  use diag;

# ---   *   ---   *   ---

# TODO: classes
#
#   canvas
#   cell
#   scene
#   entity

# TODO: diag
#
#   dialog choices
#   > highlight/de-highlight selected
#   > adapt it to lycon-queue model

# ---   *   ---   *   ---
# global state

my %CACHE=(

  -TERMINATE=>0,
  -CMENU=>undef,

);

# ---   *   ---   *   ---
# getters

;;sub TERMINATE {
  avt::getset(\%CACHE,-TERMINATE,shift);

};sub CMENU {
  avt::getset(\%CACHE,-CMENU,shift);

};

# ---   *   ---   *   ---

my $scroll_up=sub {CMENU->sel_prev();};
my $scroll_down=sub {CMENU->sel_next();};

# ---   *   ---   *   ---

my @KEYS=(

  [-AFWD,'up',$scroll_up,'',''],
  [-ABAK,'down',$scroll_down,'',''],

  [-ALFT,'left','','',''],
  [-ARGT,'right','','',''],

  [-RET,'ret','','',''],
  [-JMP,'space','','',''],

  [-ESC,'escape','','',
    sub {TERMINATE(1);}

  ],

);

# ---   *   ---   *   ---

lycon::nit();
CMENU(diag::nit());

for my $keyset(@KEYS) {

  lycon::kbd::DEFINE(
    @$keyset

  );

};lycon::kbd::nit();
lycon::clk::nit(0x8000);

lycon::loop::set_quit(sub {return TERMINATE;});
lycon::loop::run();

# ---   *   ---   *   ---
1; # ret
