#!/usr/bin/perl
#
# dicerolls
#
# ---   *   ---   *   ---

# deps

  use v5.36.0;
  use strict;
  use warnings;

  use Time::HiRes qw(usleep);
  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';
  use Style;

  use lib $ENV{'ARPATH'}.'/lib/';
  use GF::Icon;
  use GF::Mode::ANSI;

  use lib $ENV{'ARPATH'}.'/THRONE/';

  use RPG::Cell;
  use RPG::Actor;
  use RPG::Magic;
  use RPG::Spell;

# ---   *   ---   *   ---
# create effects

sub damage($self,$M) {

  my $dmg   = $M->{mag}/2;

  my $attrs = $M->{dst}->{attrs};
  my $key   = $self->key();

  $attrs->{$key}->mod_current(-$dmg);

};

sub _bless($self,$M) {
  $M->{mag}+=$M->{mag}/2;

};

sub evil($self,$M) {

  my $dice = $M->{spell}->{dice};

  my $dst  = $M->{dst};
  my $mag  = $M->{mag};

  $M->{mag} = 2/$mag;
  $M->{dst} = $M->{src};

  damage($self,$M);

  $M->{mag} = $mag * 1.5;
  $M->{dst} = $dst;

};

sub poison($self,$M) {

  my $spell = $M->{spell};
  my $dst   = $M->{dst};
  my $mag   = $M->{mag};

  my $first =! exists $M->{dur};

  $M->{dur} //= $spell->{dur}+1;


  $dst->{eff}->add(\&poison,$self,$M)
  if 0 < $M->{dur}--;

  if(! $first) {

    $M->{mag}=$mag/2;
    damage($self,$M);

    print

      "\e[0H\e[0K$M->{dst}->{name} takes "
    . ($M->{mag}/2) . ' '

    . " poison damage!"

    ;

    $mag+=$M->{mag}*0.25;

  };

  $M->{mag}=$mag;

};

# ---   *   ---   *   ---
# ^add to table

RPG::Magic->new(

  'attack' => \&damage,

  tab=>{
    key=>'hp',

  },

);

RPG::Magic->new(
  'bless' => \&_bless,

);

RPG::Magic->new(

  'evil' => \&evil,

  tab=>{
    key=>'hp',

  },

);

RPG::Magic->new(

  'poison' => \&poison,

  tab=>{
    key=>'hp',

  },

);

# ---   *   ---   *   ---
# ^fill out the grimoire

RPG::Spell->new(

  name   => 'Slash',
  school => 'Combat',

  degree => 0,
  eff    => ['attack'],

  desc   => 'Cuts your target!'

);

RPG::Spell->new(

  name   => 'Snake Venom',
  school => 'Night',

  degree => 3,
  dur    => 2,

  eff    => ['evil','poison','attack'],

  desc   => 'Damages the enemy over time',

);

RPG::Spell->new(

  name   => 'Smite',
  schhol => 'Faith',

  degree => 2,
  eff    => ['bless','bless','attack'],

  desc   => 'Doubly righteous attack',

);

RPG::Spell->new(

  name   => 'Holy Slash',
  school => 'Faith',

  degree => 1,
  eff    => ['bless','attack'],

  desc   => 'Cuts your target -- righteously!'

);

RPG::Spell->new(

  name   => 'Unholy Slash',
  school => 'Faith',

  degree => 2,
  eff    => ['bless','evil','attack'],

  desc   => 'Cuts your target -- maliciously!'

);

# ---   *   ---   *   ---
# make map

my $arena=RPG::Cell->new(

  'imp_arena_00',

  name => 'The Imperium Arena',
  co   => [0,0],

);

# ---   *   ---   *   ---
# make dude

my $jack=RPG::Actor->new(

  name => 'Jack',

  cell => $arena,
  pos  => [0,0],

  grim => ['Slash','Holy Slash','Smite'],

);

my $jane=RPG::Actor->new(

  name => 'Jane',

  cell => $arena,
  pos  => [2,3],

  grim => ['Slash','Unholy Slash','Snake Venom'],

);

# ---   *   ---   *   ---
# switchable viewpoints

my $other = $jack;
my $self  = $jane;

# ---   *   ---   *   ---
# drawing bars

my $f=GF::Mode::ANSI->new_frame();

sub draw_bars(@actors) {

  while(1) {

    my $co     = [0,3];
    my $redraw = 0;

    map {

      my ($updated,@cmd)=
        $ARG->draw_bars(pos=>$co);

      $redraw|=$updated;
      $f->req(@cmd);

    } @actors;

    $f->draw();
    usleep(10000);


    last if ! $redraw;

  };

};

# ---   *   ---   *   ---

while(

   $self->alive()
&& $other->alive()

) {

  print "\e[0H\e[0K";

  my $spell=$self->take_turn() or last;
  draw_bars($jane,$jack);


  $self->cast($spell->{name},$other);

  print

    "\e[0H\e[0K"

  . "$self->{name} uses "
  . "$spell->{name} "

  . "on $other->{name}!"

  ;

  draw_bars($jane,$jack);

  usleep(20000);
  ($self,$other)=($other,$self);

};

draw_bars($jane,$jack);
say "\e[20H\e[0K";

my @victor=grep {$ARG->alive()} ($jane,$jack);
my @defeat=grep {! $ARG->alive()} ($jane,$jack);

map {
  say "$ARG->{name} died an inglorious death!"

} @defeat;

map {
  say "$ARG->{name} is victorious!"

} @victor;

say "Everyone is dead! ASFAIMAS rejoices!"
if ! @victor;

# ---   *   ---   *   ---
1; # ret
