#!/usr/bin/perl
#
# dicerolls
#
# ---   *   ---   *   ---

# deps

  use v5.36.0;
  use strict;
  use warnings;

  use Time::HiRes qw(usleep);
  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';
  use Style;

  use lib $ENV{'ARPATH'}.'/lib/';
  use GF::Icon;
  use GF::Mode::ANSI;

  use lib $ENV{'ARPATH'}.'/THRONE/';

  use RPG::Cell;
  use RPG::Actor;
  use RPG::Magic;
  use RPG::Spell;

# ---   *   ---   *   ---
# create effect

sub damage($self,$M) {

  my $dmg   = $M->{mag}/2.55;

  my $attrs = $M->{dst}->{attrs};
  my $key   = $self->key();

  $attrs->{$key}->mod_current(-$dmg);

};

# ---   *   ---   *   ---
# ^add to table

RPG::Magic->new(

  'Attack' => \&damage,

  tab=>{
    key=>'hp',

  },

);

# ---   *   ---   *   ---
# ^fill out the grimoire

RPG::Spell->new(

  name   => 'Slash',
  school => 'Martial',

  degree => 0,
  eff    => ['Attack'],

  desc   => 'Cuts your target!'

);

# ---   *   ---   *   ---
# make map

my $arena=RPG::Cell->new(

  'imp_arena_00',

  name => 'The Imperium Arena',
  co   => [0,0],

);

# ---   *   ---   *   ---
# make dude

my $jack=RPG::Actor->new(

  name => 'Jack',

  cell => $arena,
  pos  => [0,0],

  grim => ['Slash'],

);

my $jane=RPG::Actor->new(

  name => 'Jane',

  cell => $arena,
  pos  => [2,3],

  grim => ['Slash'],

);

# ---   *   ---   *   ---
# switchable viewpoints

my $other = $jack;
my $self  = $jane;

# ---   *   ---   *   ---
# test

my $f=GF::Mode::ANSI->new_frame();

while($self->alive() && $other->alive()) {

  $self->cast('Slash',$other);

  print
    "\e[0H",
    "$self->{name} attacks $other->{name}!"

  ;

  while(1) {

    my $co     = [0,3];
    my $redraw = 0;

    map {

      my ($updated,@cmd)=$ARG->draw_bars(pos=>$co);

      $redraw|=$updated;
      $f->req(@cmd);

    } ($jane,$jack);

    $f->draw();
    usleep(1000);

    last if ! $redraw;

  };

  ($self,$other)=($other,$self);

};

say "\n\n";

my ($victor)=grep {$ARG->alive()} ($jane,$jack);
my ($defeat)=grep {! $ARG->alive()} ($jane,$jack);

say "$defeat->{name} died an inglorious death!";
say "$victor->{name} is victorious!";

# ---   *   ---   *   ---
1; # ret
